name: Generate and Deploy Documentation

on:
  # Executa quando houver push na branch main
  push:
    branches:
      - main
  # Permite execução manual do workflow
  workflow_dispatch:

env:
  TARGET_REPOSITORY: ${{ vars.TARGET_REPOSITORY || 'lmtani/sscita-assembly-pipelines' }}

# Define permissões necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que apenas um deploy rode por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout wdl2docs
        uses: actions/checkout@v4
        with:
          path: wdl2docs
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install wdl2docs
        run: |
          cd wdl2docs
          pip install -e .
      
      - name: Clone target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          path: target-repo
      
      - name: Generate documentation
        run: |
          mkdir -p docs-output
          wdl2doc generate target-repo -o docs-output
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
